export const Images = {
  Crew_1: require("../assets/images/Crew_1.png"),
  Crew_2: require("../assets/images/Crew_2.png"),
  Crew_3: require("../assets/images/Crew_3.png"),
  Crew_4: require("../assets/images/Crew_4.png"),
  Crew_BackGroundImg: require("../assets/images/Crew_BackGroundImg.png"),
  Destination_1: require("../assets/images/Destination_1.png"),
  Destination_2: require("../assets/images/Destination_2.png"),
  Destination_3: require("../assets/images/Destination_3.png"),
  Destination_4: require("../assets/images/Destination_4.png"),
  Destination_BackGroundImg: require("../assets/images/Destination_BackGroundImg.png"),
  Technology_1: require("../assets/images/Technology_1.png"),
  Technology_2: require("../assets/images/Technology_2.png"),
  Technology_3: require("../assets/images/Technology_3.png"),
  Technology_BackGroundImg: require("../assets/images/Technology_BackGroundImg.png"),
  Technology_Tablet_1: require("../assets/images/Technology_Tablet_1.png"),
  Technology_Tablet_2: require("../assets/images/Technology_Tablet_2.png"),
  Technology_Tablet_3: require("../assets/images/Technology_Tablet_3.png"),
  Error_Page: require("../assets/images/Error_Page.jpg"),
};
